version: '3'

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: testello-php
    restart: always
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: testello-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - laravel

  mysql:
    container_name: testello-mysql
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testello
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local